# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ASvOwztjjz3OSW2nRZnFhET8xSologWQ
"""

# train_bcs.py — Shouvik | DenseNet121 | BCS Task
# Save to: D:\T25301094 P2\workspaces\shouvik\train_bcs.py

import os
import time
import random
import numpy as np
import pandas as pd
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from torch.optim.lr_scheduler import StepLR
import timm
from tqdm import tqdm
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# ─── Seed ───────────────────────────────────────────────────────────────────
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {DEVICE}")

# ─── CBAM ────────────────────────────────────────────────────────────────────
class ChannelAttention(nn.Module):
    def __init__(self, in_channels, reduction=16):
        super().__init__()
        self.avg_pool = nn.AdaptiveAvgPool2d(1)
        self.max_pool = nn.AdaptiveMaxPool2d(1)
        self.fc = nn.Sequential(
            nn.Linear(in_channels, in_channels // reduction),
            nn.ReLU(),
            nn.Linear(in_channels // reduction, in_channels)
        )
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg = self.fc(self.avg_pool(x).squeeze(-1).squeeze(-1))
        max_ = self.fc(self.max_pool(x).squeeze(-1).squeeze(-1))
        return x * self.sigmoid(avg + max_).unsqueeze(-1).unsqueeze(-1)


class SpatialAttention(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(2, 1, kernel_size=7, padding=3)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        avg = torch.mean(x, dim=1, keepdim=True)
        max_, _ = torch.max(x, dim=1, keepdim=True)
        return x * self.sigmoid(self.conv(torch.cat([avg, max_], dim=1)))


class CBAM(nn.Module):
    def __init__(self, in_channels):
        super().__init__()
        self.ca = ChannelAttention(in_channels)
        self.sa = SpatialAttention()

    def forward(self, x):
        return self.sa(self.ca(x))


# ─── Model ───────────────────────────────────────────────────────────────────
class DenseNet121BCS(nn.Module):
    def __init__(self, num_classes=5):
        super().__init__()
        self.backbone = timm.create_model(
            'densenet121', pretrained=True, global_pool='', num_classes=0
        )
        feature_dim = self.backbone.num_features  # 1024 for DenseNet121
        self.cbam = CBAM(feature_dim)
        self.pool = nn.AdaptiveAvgPool2d(1)
        self.head = nn.Linear(feature_dim, num_classes - 1)  # CORAL: 4 nodes

    def forward(self, x):
        feat = self.backbone(x)       # (B, 1024, H, W)
        feat = self.cbam(feat)        # (B, 1024, H, W)
        feat = self.pool(feat)        # (B, 1024, 1, 1)
        feat = feat.view(feat.size(0), -1)  # (B, 1024)
        logits = self.head(feat)      # (B, 4)
        return logits


# ─── CORAL Loss ──────────────────────────────────────────────────────────────
def coral_loss(logits, labels, num_classes=5):
    sets = [(labels > i).float() for i in range(num_classes - 1)]
    labels_stacked = torch.stack(sets, dim=1)
    return F.binary_cross_entropy_with_logits(logits, labels_stacked)


def coral_predict(logits):
    return (torch.sigmoid(logits) > 0.5).sum(dim=1)


# ─── Dataset ─────────────────────────────────────────────────────────────────
class BCSDataset(Dataset):
    def __init__(self, df, label_map, transform):
        self.df = df.reset_index(drop=True)
        self.label_map = label_map
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        img = Image.open(row['image_path']).convert('RGB')
        img = self.transform(img)
        label = self.label_map[row['label']]
        return img, torch.tensor(label, dtype=torch.long)


# ─── Transforms ──────────────────────────────────────────────────────────────
MEAN = [0.485, 0.456, 0.406]
STD  = [0.229, 0.224, 0.225]

train_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(15),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])

val_tf = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])


# ─── Metrics ─────────────────────────────────────────────────────────────────
def compute_metrics(model, loader, num_classes=5):
    model.eval()
    all_preds, all_labels = [], []
    with torch.no_grad():
        for imgs, labels in loader:
            imgs = imgs.to(DEVICE)
            logits = model(imgs)
            preds = coral_predict(logits).cpu()
            all_preds.append(preds)
            all_labels.append(labels)
    preds  = torch.cat(all_preds).numpy()
    labels = torch.cat(all_labels).numpy()
    mae    = float(np.mean(np.abs(preds - labels)))
    acc0   = float(np.mean(preds == labels))
    acc1   = float(np.mean(np.abs(preds - labels) <= 1))
    return mae, acc0, acc1


# ─── Training Loop ───────────────────────────────────────────────────────────
def train_one_dataset(
    dataset_name, csv_path, label_map,
    checkpoint_name, workspace, batch_size=32, epochs=30, num_classes=5
):
    print(f"\n{'='*60}")
    print(f"  TRAINING ON: {dataset_name}")
    print(f"{'='*60}\n")

    df = pd.read_csv(csv_path)
    df['label'] = df['label'].apply(lambda x: float(x) if '.' in str(x) else int(x))

    train_df = df[df['split'] == 'train']
    val_df   = df[df['split'] == 'val']
    test_df  = df[df['split'] == 'test']

    print(f"Train: {len(train_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

    train_ds = BCSDataset(train_df, label_map, train_tf)
    val_ds   = BCSDataset(val_df,   label_map, val_tf)
    test_ds  = BCSDataset(test_df,  label_map, val_tf)

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,  num_workers=4, pin_memory=True)
    val_loader   = DataLoader(val_ds,   batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=True)
    test_loader  = DataLoader(test_ds,  batch_size=batch_size, shuffle=False, num_workers=4, pin_memory=True)

    model = DenseNet121BCS(num_classes=num_classes).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    scheduler = StepLR(optimizer, step_size=10, gamma=0.5)

    best_val_mae = float('inf')
    checkpoint_path = os.path.join(workspace, checkpoint_name)

    history = {
        'train_loss': [],
        'val_mae': [],
        'epoch_loss_at': {}
    }

    start_time = time.time()

    for epoch in range(1, epochs + 1):
        model.train()
        running_loss = 0.0

        pbar = tqdm(train_loader, desc=f"[{dataset_name}] Epoch {epoch:02d}/{epochs}", leave=True)
        for imgs, labels in pbar:
            imgs, labels = imgs.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            logits = model(imgs)
            loss = coral_loss(logits, labels, num_classes)
            loss.backward()
            optimizer.step()
            running_loss += loss.item() * imgs.size(0)
            pbar.set_postfix({'loss': f'{loss.item():.4f}'})

        epoch_loss = running_loss / len(train_ds)
        val_mae, val_acc0, val_acc1 = compute_metrics(model, val_loader, num_classes)

        history['train_loss'].append(epoch_loss)
        history['val_mae'].append(val_mae)

        if epoch in [10, 20, 30]:
            history['epoch_loss_at'][epoch] = epoch_loss

        print(f"  → Epoch {epoch:02d} | Train Loss: {epoch_loss:.4f} | Val MAE: {val_mae:.4f} | "
              f"Acc±0: {val_acc0*100:.2f}% | Acc±1: {val_acc1*100:.2f}%")

        if val_mae < best_val_mae:
            best_val_mae = val_mae
            torch.save(model.state_dict(), checkpoint_path)
            print(f"  ✓ Best model saved → {checkpoint_name} (Val MAE: {best_val_mae:.4f})")

        scheduler.step()

    elapsed = (time.time() - start_time) / 60.0
    print(f"\n  Training complete in {elapsed:.1f} minutes.")

    # ── Load best and evaluate test ──
    model.load_state_dict(torch.load(checkpoint_path, map_location=DEVICE))
    test_mae, test_acc0, test_acc1 = compute_metrics(model, test_loader, num_classes)

    print(f"\n  TEST RESULTS ({dataset_name}):")
    print(f"  Test MAE     : {test_mae:.4f}")
    print(f"  Test Acc ±0  : {test_acc0*100:.2f}%")
    print(f"  Test Acc ±1  : {test_acc1*100:.2f}%")

    result = {
        'dataset'       : dataset_name,
        'epochs_trained': epochs,
        'loss_ep10'     : history['epoch_loss_at'].get(10, 'N/A'),
        'loss_ep20'     : history['epoch_loss_at'].get(20, 'N/A'),
        'loss_ep30'     : history['epoch_loss_at'].get(30, 'N/A'),
        'final_train_loss': history['train_loss'][-1],
        'val_mae'       : best_val_mae,
        'val_acc0'      : val_acc0,
        'val_acc1'      : val_acc1,
        'test_mae'      : test_mae,
        'test_acc0'     : test_acc0,
        'test_acc1'     : test_acc1,
        'checkpoint'    : checkpoint_path,
        'train_time_min': elapsed,
        'train_loss_hist': history['train_loss'],
        'val_mae_hist'  : history['val_mae'],
    }
    return result


# ─── Save Results TXT ────────────────────────────────────────────────────────
def save_results_txt(workspace, r1, r2):
    path = os.path.join(workspace, 'bcs_results.txt')

    def fmt_loss(v):
        return f"{v:.4f}" if isinstance(v, float) else str(v)

    lines = [
        "---CONTEXT 3 BCS---",
        "PERSON NAME: Shouvik",
        "BASE MODEL: DenseNet121",
        "",
        f"DATASET: {r1['dataset']}",
        f"EPOCHS TRAINED: {r1['epochs_trained']}",
        f"LOSS AT EPOCH 10: {fmt_loss(r1['loss_ep10'])}",
        f"LOSS AT EPOCH 20: {fmt_loss(r1['loss_ep20'])}",
        f"LOSS AT EPOCH 30: {fmt_loss(r1['loss_ep30'])}",
        f"FINAL TRAIN LOSS: {fmt_loss(r1['final_train_loss'])}",
        f"VAL MAE: {r1['val_mae']:.4f}",
        f"VAL ACCURACY +-0 (exact match): {r1['val_acc0']*100:.2f}%",
        f"VAL ACCURACY +-1 (within 1 class): {r1['val_acc1']*100:.2f}%",
        f"TEST MAE: {r1['test_mae']:.4f}",
        f"TEST ACCURACY +-0: {r1['test_acc0']*100:.2f}%",
        f"TEST ACCURACY +-1: {r1['test_acc1']*100:.2f}%",
        f"CHECKPOINT PATH: {r1['checkpoint']}",
        f"TRAINING TIME (mins): {r1['train_time_min']:.1f}",
        "ANY ISSUES ENCOUNTERED: None",
        "",
        f"DATASET: {r2['dataset']}",
        f"EPOCHS TRAINED: {r2['epochs_trained']}",
        f"LOSS AT EPOCH 10: {fmt_loss(r2['loss_ep10'])}",
        f"LOSS AT EPOCH 20: {fmt_loss(r2['loss_ep20'])}",
        f"LOSS AT EPOCH 30: {fmt_loss(r2['loss_ep30'])}",
        f"FINAL TRAIN LOSS: {fmt_loss(r2['final_train_loss'])}",
        f"VAL MAE: {r2['val_mae']:.4f}",
        f"VAL ACCURACY +-0 (exact match): {r2['val_acc0']*100:.2f}%",
        f"VAL ACCURACY +-1 (within 1 class): {r2['val_acc1']*100:.2f}%",
        f"TEST MAE: {r2['test_mae']:.4f}",
        f"TEST ACCURACY +-0: {r2['test_acc0']*100:.2f}%",
        f"TEST ACCURACY +-1: {r2['test_acc1']*100:.2f}%",
        f"CHECKPOINT PATH: {r2['checkpoint']}",
        f"TRAINING TIME (mins): {r2['train_time_min']:.1f}",
        "ANY ISSUES ENCOUNTERED: None",
        "---END CONTEXT 3---",
    ]
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"\n  ✓ bcs_results.txt saved → {path}")


# ─── Save Loss Curve ──────────────────────────────────────────────────────────
def save_loss_curve(workspace, r1, r2):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    for ax, r in zip(axes, [r1, r2]):
        epochs = range(1, len(r['train_loss_hist']) + 1)
        ax.plot(epochs, r['train_loss_hist'], label='Train Loss', color='steelblue')
        ax2 = ax.twinx()
        ax2.plot(epochs, r['val_mae_hist'], label='Val MAE', color='tomato', linestyle='--')
        ax.set_xlabel('Epoch')
        ax.set_ylabel('Train Loss', color='steelblue')
        ax2.set_ylabel('Val MAE', color='tomato')
        ax.set_title(f"DenseNet121 — {r['dataset']}")
        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2, loc='upper right')

    plt.tight_layout()
    path = os.path.join(workspace, 'bcs_loss_curve.png')
    plt.savefig(path, dpi=150)
    plt.close()
    print(f"  ✓ bcs_loss_curve.png saved → {path}")


# ─── Main ────────────────────────────────────────────────────────────────────
if __name__ == '__main__':
    WORKSPACE   = r"D:\T25301094 P2\workspaces\shouvik"
    BATCH_SIZE  = 32
    EPOCHS      = 30
    NUM_CLASSES = 5

    # ── Run 1: Dryad ──
    dryad_result = train_one_dataset(
        dataset_name    = 'Dryad',
        csv_path        = r"D:\T25301094 P2\datasets\bcs\bcs_index.csv",
        label_map       = {2: 0, 3: 1, 4: 2, 5: 3, 6: 4},
        checkpoint_name = 'dryad_bcs_best.pth',
        workspace       = WORKSPACE,
        batch_size      = BATCH_SIZE,
        epochs          = EPOCHS,
        num_classes     = NUM_CLASSES,
    )

    # ── Run 2: ScienceDB ──
    sciencedb_result = train_one_dataset(
        dataset_name    = 'ScienceDB',
        csv_path        = r"D:\T25301094 P2\datasets\bcs\sciencedb_bcs_index.csv",
        label_map       = {3.25: 0, 3.5: 1, 3.75: 2, 4.0: 3, 4.25: 4},
        checkpoint_name = 'sciencedb_bcs_best.pth',
        workspace       = WORKSPACE,
        batch_size      = BATCH_SIZE,
        epochs          = EPOCHS,
        num_classes     = NUM_CLASSES,
    )

    # ── Save outputs ──
    save_results_txt(WORKSPACE, dryad_result, sciencedb_result)
    save_loss_curve(WORKSPACE,  dryad_result, sciencedb_result)

    print("\n  ALL DONE. Share bcs_results.txt with Hasin.")